COMPL = gcc
hfiles = \
	iniparser.h

ofiles = \
	iniparser.o

%.o:%.c 
	$(COMPL) -g -c  $<  

objects: $(ofiles) $(hfiles)




#correct:correct_t.cpp $(ofiles) $(hfiles)
#	g++ -g correct_t.cpp -o correct -I /export/data/Grenoble/ALASKADATA/modules  $(ofiles) -lfftw3f 
#	writegse.o\
#	X_corr.o\
