all: testsafromseed testcuttransmod testdowhiten

testsafromseed:
		python test_modules.py -c testdata/sa_from_seed_new_test.cfg

testcuttransmod:
		python test_modules.py -c testdata/cut_trans_mod_test.cfg	

testdowhiten:
		python test_modules.py -c testdata/do_whiten_test.cfg	

testdowhitenew:
		python test_modules.py -c testdata/do_whiten_new_test.cfg	
