testsafromseed:
		python test_modules.py -c testdata/sa_from_seed_mod_test.cfg

testcuttransmod:
		python test_modules.py -c testdata/cut_trans_mod_test.cfg	

testdowhiten:
		python test_modules.py -c testdata/do_whiten_test.cfg	

